import java.io.StreamTokenizer;
import java.io.StringReader;
import java.util.ArrayDeque;
import java.util.Deque;

// VM/interpreter for running non standard dc code. Only made to work with code generated by this compiler
public class dcVM {
    private static String prog = "5\nsa\n0 k\nla\n5 k\n3.2\n+\nsb\n0 k\nlb\np\nsi";
    private static Deque<Double> stack = new ArrayDeque<Double>();
    private static double[] registers = new double[26];

    public static void main(String[] args) throws Exception {

        StreamTokenizer tokenizer = new StreamTokenizer(new StringReader(prog));

        while (tokenizer.nextToken() != StreamTokenizer.TT_EOF) {
            switch (tokenizer.ttype) {
                case StreamTokenizer.TT_WORD:
                    String word = tokenizer.sval;
                    char opcode = word.charAt(0);
                    int reg;
                    switch (opcode) {
                        case 's':
                            reg = word.charAt(1) - 'a';
                            registers[reg] = stack.pop();
                            break;
                        case 'l':
                            reg = word.charAt(1) - 'a';
                            stack.push(registers[reg]);
                            break;
                        case 'p':
                            System.out.print(stack.peek());
                            break;
                        case 'k':
                            stack.pop();
                            break;
                        default:
                            System.err.println("Unknown opcode: " + tokenizer);
                    }
                    break;
                case StreamTokenizer.TT_NUMBER:
                    stack.push(tokenizer.nval);
                    break;
                case '+':
                    stack.push(stack.pop() + stack.pop());
                    break;
                case '-':
                    stack.push(stack.pop() - stack.pop());
                    break;
                default:
                    System.err.println("Unknown token: " + tokenizer);
            }
        }
    }
}
